apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-prices-grpc-deployment
  labels:
    app: ecommerce-prices-grpc
spec:
  replicas: 3 # Initial replicas for gRPC, adjust as needed
  selector:
    matchLabels:
      app: ecommerce-prices-grpc
  template:
    metadata:
      labels:
        app: ecommerce-prices-grpc
    spec:
      containers:
        - name: ecommerce-prices-app
          image: ACR/ecommerce-prices:latest # Same image as web
          ports:
            - containerPort: 9090 # Expose only the gRPC port
              name: grpc-port
          resources: # Tailored for gRPC
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command:
                - grpc-health-probe
                - -addr=localhost:9090
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - grpc-health-probe
                - -addr=localhost:9090
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
      imagePullSecrets:
        - name: acr-secret